package com.dreamsoftware.lockbuddy.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF0D47A1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7687D7)
val md_theme_light_onPrimaryContainer = Color(0xFF1D1D1F)
val md_theme_light_secondary = Color(0xFF388E3C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF5FA65F)
val md_theme_light_onSecondaryContainer = Color(0xFF1D1D1F)
val md_theme_light_tertiary = Color(0xFFE87E42)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE0B2)
val md_theme_light_onTertiaryContainer = Color(0xFF1D1D1F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFC2C9FF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFB9B9C3)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF85868F)
val md_theme_light_inverseOnSurface = Color(0xFFF3EFF4)
val md_theme_light_inverseSurface = Color(0xFF313034)
val md_theme_light_inversePrimary = Color(0xFFBFC2FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8F97C3)
val md_theme_light_outlineVariant = Color(0xFFC7C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF0D47A1)
val md_theme_dark_onPrimary = Color(0xFF181B90)
val md_theme_dark_primaryContainer = Color(0xFF5866C7)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
val md_theme_dark_secondary = Color(0xFF388E3C)
val md_theme_dark_onSecondary = Color(0xFF2E2F42)
val md_theme_dark_secondaryContainer = Color(0xFF4E6A4E)
val md_theme_dark_onSecondaryContainer = Color(0xFFE1E0F9)
val md_theme_dark_tertiary = Color(0xFFE8B9D4)
val md_theme_dark_onTertiary = Color(0xFF46263B)
val md_theme_dark_tertiaryContainer = Color(0xFF5F3C52)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8ED)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF31353A)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF4C4C55)
val md_theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val md_theme_dark_outline = Color(0xFF85868F)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF4C52BF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF6B74A7)
val md_theme_dark_outlineVariant = Color(0xFF46464F)
val md_theme_dark_scrim = Color(0xFF000000)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val Blue = Color(0xFF2196F3)
val LightBlue = Color(0xFF79B7E9)
val White = Color(0xFFEBEBEB)
val Gray = Color(0xD3515151)
val LightGray = Color(0xD3BBBBBB)
val LightBlack = Color(0xD3323232)
val BgBlack = Color.Black
val Red = Color(0xD3E72121)
